import { PHONE_AUTO_ACTIONS } from '../../phone-tools';
import { PLANNING_ACTION_NAMES } from '../planning-tools';
import { GAP_AUTO_ACTIONS } from '../gap-closing-tools';

export const AUTO_ACTION_NAMES = new Set([
  'navigateTo',
  'navigate',
  'writeData',
  'getTeamPerformance',
  'searchLeads',
  'updateLeadStatus',
  'logFollowUp',
  'getLeadBrief',
  'addLeadNote',
  'listPendingCallbacks',
  'addQuoteLines',
  'updateQuoteLines',
  'completeHandover',
  'assignContractor',
  'markPaymentReceived',
  'sendBuilderBrief',
  'sendContractorBrief',
  'requestSitePhotos',
  'relayCustomerUpdate',
  'logBuilderReply',
  'notifyCustomerChangeOrder',
  'escalateToStaff',
  'recordCostEntry',
  'logHours',
  'categorizeTransaction',
  'matchTransactionToProject',
  'draftClientReceipt',
  'listRecentEmails',
  'getEmailThread',
  'draftEmailReply',
  'sendEmailReply',
  'sendEmailWithAttachment',
  'draftQuote',
  'generateQuotePdf',
  'generateOpsReport',
  'sendToStaffCynthia',
  'requestCodeFix',
  'placeOutboundCall',
  ...PHONE_AUTO_ACTIONS,
  ...PLANNING_ACTION_NAMES,
  ...GAP_AUTO_ACTIONS,
  'getMenu',
  'upsertMenuItem',
  'deleteMenuItem',
  'listOrders',
  'markOrderPaid',
  'updateOrderStatus',
]);
