# -*- coding: utf-8 -*-
#!/usr/bin/env python3
"""Generate Asterisk pjsip.conf + extensions.conf for N concurrent Soho66 REGISTERs.

Reads a full line set from LINES_JSON_FILE (default /opt/lines.json). Each entry is
one Soho66 SIP login (a customer Judie line or Sally) that must register independently
and route its inbound calls to its own Vapi number. If the file is missing/empty the
bridge falls back to the single-line environment variables (backward compatible).

Inbound routing uses PJSIP line=yes: each REGISTER carries a line token, so Soho66's
inbound INVITE is matched to that registration's endpoint/context - even though every
line shares the same Soho66 SBC source IPs. No IP-based identify is needed or wanted.
"""
import json
import os
import re
import sys

PJSIP_PATH = "/etc/asterisk/pjsip.conf"
EXT_PATH = "/etc/asterisk/extensions.conf"

EXTERNAL_IP = os.environ.get("EXTERNAL_IP", "").strip()
SOHO66_PORT = os.environ.get("SOHO66_SIP_PORT", "8060").strip() or "8060"
AI_SIP_PORT = os.environ.get("AI_SIP_PORT", "5060").strip() or "5060"
AI_SIP_TRANSPORT = os.environ.get("AI_SIP_TRANSPORT", "udp").strip() or "udp"

# Env fallbacks (single-line legacy mode)
ENV_USER = os.environ.get("SOHO66_SIP_USERNAME", "").strip()
ENV_PASS = os.environ.get("SOHO66_SIP_PASSWORD", "").strip()
ENV_DOMAIN = os.environ.get("SOHO66_SIP_DOMAIN", "sbc.soho66.co.uk").strip()
ENV_VAPI_USER = os.environ.get("VAPI_INBOUND_USER", "").strip()
ENV_AI_HOST = os.environ.get("AI_SIP_HOST", "").strip()

LINES_FILE = os.environ.get("LINES_JSON_FILE", "/opt/lines.json")


def load_lines():
    raw = None
    if os.path.isfile(LINES_FILE):
        try:
            with open(LINES_FILE) as fh:
                raw = fh.read().strip()
        except Exception as exc:
            print("WARN: could not read %s: %s" % (LINES_FILE, exc), file=sys.stderr)
    lines = []
    if raw:
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, list):
                lines = parsed
        except Exception as exc:
            print("WARN: %s is not valid JSON: %s" % (LINES_FILE, exc), file=sys.stderr)

    normalized = []
    for entry in lines:
        user = str(entry.get("sipUsername", "")).strip()
        pwd = str(entry.get("sipPassword", "")).strip()
        domain = str(entry.get("sipDomain", "")).strip() or ENV_DOMAIN
        vapi_user = str(entry.get("vapiUser") or entry.get("didE164") or "").strip()
        ai_host = str(entry.get("aiSipHost", "")).strip() or ENV_AI_HOST
        if not (user and pwd and vapi_user and ai_host):
            print("SKIP line %s: missing user/pass/vapiUser/aiHost" % (user or "(no user)"), file=sys.stderr)
            continue
        normalized.append(
            {
                "user": user,
                "pass": pwd,
                "domain": domain,
                "vapi_user": vapi_user,
                "ai_host": ai_host,
                "label": str(entry.get("label", user)),
                "purpose": str(entry.get("purpose", "aria")),
            }
        )

    if not normalized and ENV_USER and ENV_PASS and ENV_VAPI_USER and ENV_AI_HOST:
        print(
            "ERROR-LEVEL WARNING: lines.json empty/missing - falling back to SINGLE-LINE env "
            "(SOHO66_SIP_USERNAME=%s). This displaces every other AI line. Prefer writing "
            "lines.json via POST /api/platform/phone-lines/sync-asterisk-bridge."
            % ENV_USER,
            file=sys.stderr,
        )
        normalized.append(
            {
                "user": ENV_USER,
                "pass": ENV_PASS,
                "domain": ENV_DOMAIN,
                "vapi_user": ENV_VAPI_USER,
                "ai_host": ENV_AI_HOST,
                "label": ENV_USER,
                "purpose": "aria",
            }
        )
    return normalized


def slug(user):
    return re.sub(r"[^A-Za-z0-9]", "", user)


HEADER = """; AUTO-GENERATED by generate.py - do not hand edit.
; N concurrent Soho66 REGISTERs to Vapi. One block per SIP login.

[global]
type=global
user_agent=sync2dine-soho66-sip-bridge/2.0

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:%(port)s
external_media_address=%(ip)s
external_signaling_address=%(ip)s
local_net=10.0.0.0/8
local_net=172.16.0.0/12
local_net=192.168.0.0/16

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:%(port)s
external_media_address=%(ip)s
external_signaling_address=%(ip)s
local_net=10.0.0.0/8
local_net=172.16.0.0/12
local_net=192.168.0.0/16
""" % {"port": SOHO66_PORT, "ip": EXTERNAL_IP}


def line_block(l):
    s = slug(l["user"])
    return """
; ===== %(label)s (%(purpose)s) - %(user)s@%(domain)s -> sip:%(vapi)s@%(host)s =====
[reg-%(s)s]
type=registration
transport=transport-udp
outbound_auth=auth-%(s)s
server_uri=sip:%(domain)s:%(port)s
client_uri=sip:%(user)s@%(domain)s
contact_user=%(user)s
retry_interval=60
forbidden_retry_interval=300
expiration=300
line=yes
endpoint=soho66-ep-%(s)s

[auth-%(s)s]
type=auth
auth_type=userpass
username=%(user)s
password=%(pass)s

[soho66-aor-%(s)s]
type=aor
contact=sip:%(domain)s:%(port)s

[soho66-ep-%(s)s]
type=endpoint
transport=transport-udp
context=from-%(s)s
disallow=all
allow=alaw
allow=ulaw
allow=g722
outbound_auth=auth-%(s)s
aors=soho66-aor-%(s)s
from_user=%(user)s
from_domain=%(domain)s
direct_media=yes
direct_media_glare_mitigation=none
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_use_received_transport=yes
ice_support=no

[ai-%(s)s]
type=endpoint
transport=transport-udp
context=to-ai
aors=ai-aor-%(s)s
disallow=all
allow=ulaw
allow=alaw
allow=g722
direct_media=yes
direct_media_glare_mitigation=none
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_use_received_transport=yes
ice_support=no
from_domain=%(host)s

[ai-aor-%(s)s]
type=aor
contact=sip:%(vapi)s@%(host)s:%(aiport)s\\;transport=%(aitrans)s
""" % {
        "label": l["label"],
        "purpose": l["purpose"],
        "user": l["user"],
        "domain": l["domain"],
        "pass": l["pass"],
        "vapi": l["vapi_user"],
        "host": l["ai_host"],
        "s": s,
        "port": SOHO66_PORT,
        "aiport": AI_SIP_PORT,
        "aitrans": AI_SIP_TRANSPORT,
    }


def ext_block(l):
    s = slug(l["user"])
    target = "PJSIP/ai-%s/sip:%s@%s" % (s, l["vapi_user"], l["ai_host"])
    return """
[from-%(s)s]
; %(label)s (%(user)s) inbound -> Vapi %(vapi)s
exten => _X.,1,NoOp(Soho66 %(user)s inbound: ${CALLERID(num)} -> ${EXTEN})
 same => n,Answer()
 same => n,Playback(silence/1)
 same => n,Dial(%(target)s,120)
 same => n,Hangup()
exten => s,1,NoOp(Soho66 %(user)s inbound s: ${CALLERID(num)})
 same => n,Answer()
 same => n,Playback(silence/1)
 same => n,Dial(%(target)s,120)
 same => n,Hangup()
""" % {"s": s, "label": l["label"], "user": l["user"], "vapi": l["vapi_user"], "target": target}


def main():
    lines = load_lines()
    if not lines:
        print("ERROR: no usable SIP lines (lines.json empty and env incomplete)", file=sys.stderr)
        sys.exit(1)

    pjsip = HEADER + "".join(line_block(l) for l in lines)
    extensions = "; AUTO-GENERATED by generate.py - do not hand edit.\n" + "".join(
        ext_block(l) for l in lines
    ) + "\n[to-ai]\nexten => _X.,1,Hangup()\n"

    with open(PJSIP_PATH, "w") as fh:
        fh.write(pjsip)
    with open(EXT_PATH, "w") as fh:
        fh.write(extensions)

    print("Generated %d SIP line(s):" % len(lines))
    for l in lines:
        print("  - %s [%s] %s@%s -> sip:%s@%s" % (
            l["label"], l["purpose"], l["user"], l["domain"], l["vapi_user"], l["ai_host"],
        ))


if __name__ == "__main__":
    main()
